name: Build Latest
on:
  push:
    branches:
      - master
    tags-ignore: ["*"]
jobs:
  build-and-deploy-latest:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'gmr/erlang-elixir'
    container: docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build and upload the image
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u gmr --password-stdin
          docker build -t ghcr.io/gmr/erlang-elixir:${GITHUB_SHA:0:7} .
          docker push ghcr.io/gmr/erlang-elixir:${GITHUB_SHA:0:7}
          docker tag ghcr.io/gmr/erlang-elixir:${GITHUB_SHA:0:7} ghcr.io/gmr/erlang-elixir:latest
          docker push ghcr.io/gmr/erlang-elixir:latest
